export const FETCH_MOBILE_SUCCESS = 'FETCH_MOBILE_SUCCESS';
export const DELETE_MOBILE_SUCCESS = 'DELETE_MOBILE_SUCCESS';
export const ADD_MOBILE_SUCCESS = 'ADD_MOBILE_SUCCESS';
export const UPDATE_MOBILE_SUCCESS = 'UPDATE_MOBILE_SUCCESS';
export const SEARCH_MOBILE_SUCCESS = "SEARCH_MOBILE_SUCCESS";